export const COMPANY_REPOS = {
  LOAD: 'COMPANY_REPOS_LOAD',
  LOAD_SUCCESS: 'COMPANY_REPOS_LOAD_SUCCESS',
  LOAD_FAIL: 'COMPANY_REPOS_LOAD_FAIL',
  CLEAR: 'COMPANY_REPOS_CLEAR'
};

export const LOADER = {
  HIDE: 'HIDE_LOADER',
  SHOW: 'SHOW_LOADER'
};